### ISSUE TITLE
Can I build tflite cpp using "offical" scripts?

### ISSUE THREAD

**Issue by imdatngo** [mattn/go-tflite#2]
I found that Tensorflow provides the build scripts for the tflite cpp lib in: [https://www.tensorflow.org/lite/guide/build_rpi](https://www.tensorflow.org/lite/guide/build_rpi)

So I'm wondering if I can use it instead? Or if not, can I simply modify something to make it compatible? Because I got the following error running the example:

```bash
pi@raspberrypi:~/go/src/github.com/mattn/go-tflite/_example/ssd $ go run main.go 
# github.com/mattn/go-tflite
../../tflite_experimental.go: In function 'writeToTensorAsVector':
../../tflite_experimental.go:64:13: error: 'TfLiteTensor {aka struct <anonymous>}' has no member named 'quantization'; did you mean 'allocation'?
   if (tensor->quantization.type == kTfLiteAffineQuantization) {
             ^~
../../tflite_experimental.go:64:36: error: 'kTfLiteAffineQuantization' undeclared (first use in this function)
   if (tensor->quantization.type == kTfLiteAffineQuantization) {
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
../../tflite_experimental.go:64:36: note: each undeclared identifier is reported only once for each function it appears in
../../tflite_experimental.go:65:5: error: unknown type name 'TfLiteAffineQuantization'
     TfLiteAffineQuantization* q_params =
     ^~~~~~~~~~~~~~~~~~~~~~~~
../../tflite_experimental.go:66:10: error: 'TfLiteAffineQuantization' undeclared (first use in this function)
         (TfLiteAffineQuantization*)(tensor->quantization.params);
          ^~~~~~~~~~~~~~~~~~~~~~~~
../../tflite_experimental.go:66:35: error: expected expression before ')' token
         (TfLiteAffineQuantization*)(tensor->quantization.params);
                                   ^
../../tflite_experimental.go:66:43: error: 'TfLiteTensor {aka struct <anonymous>}' has no member named 'quantization'; did you mean 'allocation'?
         (TfLiteAffineQuantization*)(tensor->quantization.params);
                                           ^~
../../tflite_experimental.go:67:17: error: request for member 'scale' in something not a structure or union
     if (q_params->scale) {
                 ^~
../../tflite_experimental.go:68:20: error: request for member 'scale' in something not a structure or union
       free(q_params->scale);
                    ^~
../../tflite_experimental.go:69:15: error: request for member 'scale' in something not a structure or union
       q_params->scale = NULL;
               ^~
../../tflite_experimental.go:71:17: error: request for member 'zero_point' in something not a structure or union
     if (q_params->zero_point) {
                 ^~
../../tflite_experimental.go:72:20: error: request for member 'zero_point' in something not a structure or union
       free(q_params->zero_point);
                    ^~
../../tflite_experimental.go:73:15: error: request for member 'zero_point' in something not a structure or union
       q_params->zero_point = NULL;
               ^~
../../tflite_experimental.go:82:9: error: 'TfLiteTensor {aka struct <anonymous>}' has no member named 'quantization'; did you mean 'allocation'?
   tensor->quantization.type = kTfLiteNoQuantization;
         ^~
../../tflite_experimental.go:82:31: error: 'kTfLiteNoQuantization' undeclared (first use in this function)
   tensor->quantization.type = kTfLiteNoQuantization;
                               ^~~~~~~~~~~~~~~~~~~~~
../../tflite_experimental.go:83:9: error: 'TfLiteTensor {aka struct <anonymous>}' has no member named 'quantization'; did you mean 'allocation'?
   tensor->quantization.params = NULL;
         ^~
````

Sorry that I have no ideas about those C stuffs! Could you please give me some advices?

**Comment by imdatngo** [comment]
FYI, here is the actual [build script](https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/lite/tools/make/build_rpi_lib.sh). I'm using tensorflow v1.13. What is the version of yours when developing this package?

**Comment by mattn** [comment]
I'm building this with tensorflow master branch. I have a plan to fix to be possible build on 1.13.

**Comment by imdatngo** [comment]
Great! Thank you for checking!
